const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const AUTH = "AUTH";
const LOGOUT = "LOGOUT";
const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";

export {
  GET_ALL_PRODUCTS,
  AUTH,
  LOGOUT,
  GET_PRODUCT_BY_ID,
  ADD_TO_CART,
  DELETE_FROM_CART,
};
